# Generated by Django 4.0.3 on 2022-03-30 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_in_years', models.CharField(blank=True, default='Меня заполнить забыл?', max_length=100)),
                ('skills', models.CharField(blank=True, default='Меня заполнить забыл?', max_length=100)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('salary_three_years', models.CharField(blank=True, default='Меня заполнить забыл?', max_length=100)),
                ('salary_five_years', models.CharField(blank=True, default='Меня заполнить забыл?', max_length=100)),
            ],
        ),
    ]
