# Generated by Django 4.0.3 on 2022-03-30 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme_21_protocols_slideshow_2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='name',
            field=models.CharField(blank=True, default='Меня заполнить забыл?', max_length=100),
        ),
    ]
